version: "3"
services:
  eufy-security-ws:
    container_name: eufy-security-ws
    image: bropat/eufy-security-ws:1.3.0
    restart: unless-stopped
    privileged: true
    group_add:
      - "1001"
    environment:
      - "USERNAME=${EUFY_USERNAME}"
      - "PASSWORD=${EUFY_PASSWORD}"
      - "COUNTRY=${EUFY_COUNTRY_CODE}"
      - "TRUSTED_DEVICE_NAME=${EUFY_DEVICE_NAME}"
    ports:
      - 3000:3000
    networks:
      - docker_macvlan:
          ipv4_address: 192.168.1.10 # this IP will show as a device on your router
      - docker_vlan_bridge:
          ipv4_address: 192.168.10.10 # this IP will show as a device on your router

  rtsp:
    container_name: rtsp-simple-server
    image: aler9/rtsp-simple-server:latest
    restart: unless-stopped
    privileged: true
    group_add:
      - "1001"
    environment:
      - "RTSP_PROTOCOLS=tcp"
    ports:
      - 8554:8554
      - 1935:1935
    networks:
      - docker_macvlan
      - docker_vlan_bridge

networks:
  docker_macvlan:
    external: true
  docker_vlan_bridge:
    external: true
