version: "3"
services:
  eufy-security-ws:
    container_name: eufy-security-ws
    image: bropat/eufy-security-ws:1.3.0
    restart: unless-stopped
    privileged: true
    group_add:
      - "1001"
    environment:
      - USERNAME="${EUFY_USERNAME}"
      - PASSWORD="${EUFY_PASSWORD}"
      - COUNTRY="${EUFY_COUNTRY_CODE}"
      - PORT=3000
    ports:
      - 3000:3000
    volumes:
      - eufy_security_ws_data:/data
    network_mode: "host"
    # networks:
    #   docker_macvlan:
    #       ipv4_address: 10.0.1.18 # this IP will show as a device on your router
    #   docker_vlan_bridge:
    #       ipv4_address: 10.0.10.18 # same as macvlan (.18) and use "vlan bridge subnet" (10)

  rtsp:
    container_name: rtsp-simple-server
    image: aler9/rtsp-simple-server:latest
    restart: unless-stopped
    privileged: true
    group_add:
      - "1001"
    environment:
      - RTSP_PROTOCOLS=tcp
    ports:
      - 8554:8554
      - 1935:1935
    network_mode: "host"
    # networks:
    #   - docker_macvlan
    #   - docker_vlan_bridge

networks:
  docker_macvlan:
    external: true
  docker_vlan_bridge:
    external: true
volumes:
  eufy_security_ws_data:
    name: eufy_security_ws_data
