version: "3.4"

services:

  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - grocy_config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9283:80
    restart: unless-stopped
    group_add:
      - "1001"
    networks:
      macvlan:
        ipv4_address: 10.0.1.16 # this IP will show as a device on your router
      vlan_bridge:
        ipv4_address: 10.0.10.16 # same as macvlan (.3) and use "vlan bridge subnet" (10)
    
  barcodebuddy:
    image: f0rc3/barcodebuddy
    restart: unless-stopped
    container_name: barcode_buddy
    ports:
      - 9980:80
    volumes:
      - barcodebuddy_config:/config
    group_add:
      - "1001"
    networks:
      macvlan:
        ipv4_address: 10.0.1.17 # this IP will show as a device on your router
      vlan_bridge:
        ipv4_address: 10.0.10.17 # same as macvlan (.3) and use "vlan bridge subnet" (10)
  
  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_db:/data/db
    group_add:
      - "1001"
    networks:
      macvlan:
        ipv4_address: 10.0.1.18 # this IP will show as a device on your router
      vlan_bridge:
        ipv4_address: 10.0.10.18 # same as macvlan (.3) and use "vlan bridge subnet" (10)

  # recipebackend:
  #   image: ghcr.io/georgegebbett/recipe-buddy-backend:latest
  #   depends_on:
  #     - "mongo"

  # recipefrontend:
  #   image: ghcr.io/georgegebbett/recipe-buddy-frontend:latest
  #   ports:
  #     - "4000:80"
  #   depends_on:
  #     - "recipebackend"

volumes:
  grocy_config:
    name: grocy_config
  mongo_db:
    name: mongo_db
  barcodebuddy_config:
    name: barcodebuddy_config

networks:
  macvlan:
    name: docker_macvlan
    external: true # created in infra_compose.yml
  vlan_bridge:
    name: docker_vlan_bridge
    external: true # created in infra_compose.yml
