version: "3.4"

services:

  grocy:
    image: linuxserver/grocy:latest
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - grocy_config:/config
    ports:
      - 9283:80
    restart: unless-stopped
    
  # barcodebuddy:
  #   image: f0rc3/barcodebuddy
  #   restart: unless-stopped
  #   container_name: barcode_buddy
  
  # mongo:
  #   image: mongo
  #   container_name: mongodb
  #   restart: unless-stopped
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: root
  #   volumes:
  #     - mongo_db:/data/db

  # recipebackend:
  #   image: ghcr.io/georgegebbett/recipe-buddy-backend:latest
  #   depends_on:
  #     - "mongo"

  # recipefrontend:
  #   image: ghcr.io/georgegebbett/recipe-buddy-frontend:latest
  #   ports:
  #     - "4000:80"
  #   depends_on:
  #     - "recipebackend"

volumes:
  grocy_config:
  # mongo_db:
