version: "3"
services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome
    ports:
      - 53/tcp # dns
      - 53/udp # dns
      - 80/tcp
      - 3000/tcp # dashboard
      - 67/udp
      - 68/tcp
      - 68/udp
      - 443/tcp
      - 853/tcp
    volumes:
      - adguard_work:/opt/adguardhome/work
      - adguard_conf:/opt/adguardhome/conf
    networks:
      macvlan:
        ipv4_address: 192.168.1.4 # this IP will show as a device on your router
      vlan_bridge:
        ipv4_address: 192.168.10.4 # same as macvlan (192) and use "vlan bridge subnet" (10)
    restart: unless-stopped

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
    name: portainer_data
  adguard_work:
    name: adguard_work
  adguard_conf:
    name: adguard_conf

# Here we define what networks are available to use by the services above
# Make sure to set the config of both macvlan and vlan_bridge as described in the guide.
networks:
  macvlan:
    name: docker_macvlan
    driver: macvlan
    enable_ipv6: false
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24 # Set to same subnet as your router and other devices
          ip_range: 192.168.1.10/27 # Available range from 192-224
          gateway: 192.168.1.1 # This is your router IP

  vlan_bridge:
    name: docker_vlan_bridge
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: 192.168.10.0/24 # subnet for all containers
          ip_range: 192.168.10.10/27 # for easier use, set to same range as under macvlan (192 to 224 here)
          gateway: 192.168.10.1 # for easier use, set to same last number as your router (1)
