version: "3"
services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome
    ports:
      - 53/tcp # dns
      - 53/udp # dns
      - 80/tcp
      - 3000/tcp # dashboard
      - 67/udp
      - 68/tcp
      - 68/udp
      - 443/tcp
      - 853/tcp
    volumes:
      - adguard_work:/opt/adguardhome/work
      - adguard_conf:/opt/adguardhome/conf
    networks:
      macvlan:
        ipv4_address: 10.0.1.4 # this IP will show as a device on your router
      vlan_bridge:
        ipv4_address: 10.0.10.4 # same as macvlan (192) and use "vlan bridge subnet" (10)
    restart: unless-stopped

  portainer:
    container_name: portainer
    image: portainer/portainer-ee:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 8000:8000
      - 9443:9443
    networks:
      macvlan:
        ipv4_address: 10.0.1.5 # this IP will show as a device on your router
      vlan_bridge:
        ipv4_address: 10.0.10.5 # same as macvlan (192) and use "vlan bridge subnet" (10)
        
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    env_file:
      - cloudflared.env
    networks:
      macvlan:
        ipv4_address: 10.0.1.3 # this IP will show as a device on your router
      vlan_bridge:
        ipv4_address: 10.0.10.3 # same as macvlan (3) and use "vlan bridge subnet" (10)

volumes:
  portainer_data:
    name: portainer_data
  adguard_work:
    name: adguard_work
  adguard_conf:
    name: adguard_conf

# Here we define what networks are available to use by the services above
# Make sure to set the config of both macvlan and vlan_bridge as described in the guide.
networks:
  macvlan:
    name: docker_macvlan
    driver: macvlan
    enable_ipv6: false
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 10.0.1.0/24 # Set to same subnet as your router and other devices
          ip_range: 10.0.1.10/27 # Available range from 192-224
          gateway: 10.0.1.1 # This is your router IP

  vlan_bridge:
    name: docker_vlan_bridge
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: 10.0.10.0/24 # subnet for all containers
          ip_range: 10.0.10.10/27 # for easier use, set to same range as under macvlan (192 to 224 here)
          gateway: 10.0.10.1 # for easier use, set to same last number as your router (1)
