version: "3"
services:
  ####
  # players
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
      # - JELLYFIN_PublishedServerUrl=http://192.168.0.5 #optional
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - '992'
    volumes:
      - jellyfin_config:/config
      - /media:/data
      - /mnt/storage/media:/nasdata
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
  ####
  # movies
  radarr:
    image: lscr.io/linuxserver/radarr:amd64-latest
    container_name: radarr
    hostname: radarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Canada/Pacific
    group_add:
      - "1001"
    volumes:
      - radarr_config:/config
      - /media:/data
      - /mnt/storage/media:/nasdata
    ports:
      - 7878:7878
    restart: unless-stopped
    # networks:
    #   docker_macvlan:
    #       ipv4_address: 10.0.1.12
    #   docker_vlan_bridge:
    #       ipv4_address: 10.0.10.12
  ####
  # tv
  sonarr:
    image: lscr.io/linuxserver/sonarr:amd64-latest
    container_name: sonarr
    hostname: Sonarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Canada/Pacific
    group_add:
      - "1001"
    volumes:
      - sonarr_config:/config
      - /media:/data
      - /mnt/storage/media:/nasdata
    ports:
      - 8991:8989
    restart: unless-stopped
    # networks:
    #   docker_macvlan:
    #       ipv4_address: 10.0.1.22
    #   docker_vlan_bridge:
    #       ipv4_address: 10.0.10.22
  ####
  # music/audio
  lidarr:
    image: lscr.io/linuxserver/lidarr:amd64-latest
    container_name: lidarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Canada/Pacific
    volumes:
      - lidarr_config:/config
      - /media:/data
      - /mnt/storage/media:/nasdata
    ports:
      - 8686:8686
    restart: unless-stopped
  lidatube:
    image: thewicklowwolf/lidatube:latest
    container_name: lidatube
    environment:
      - PUID=1001
      - PGID=1001
    volumes:
      - lidatube_config:/lidatube/config
      - /media/music:/lidatube/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5000:5000
    restart: unless-stopped
  ####
  # indexers/trackers
  jackett:
    image: lscr.io/linuxserver/jackett:amd64-latest
    container_name: jackett
    hostname: jackett
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Canada/Pacific
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    group_add:
      - "1001"
    volumes:
      - jackett_config:/config
      - /media/downloads/torrents:/data/downloads/torrents
      - /mnt/storage/media/downloads/torrents:/nasdata/downloads/torrents
    ports:
      - 9117:9117
    restart: unless-stopped
    # networks:
    #   docker_macvlan:
    #       ipv4_address: 10.0.1.14
    #   docker_vlan_bridge:
    #       ipv4_address: 10.0.10.14
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Canada/Pacific
    volumes:
      - prowlarr_config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  ####
  # downloader
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:amd64-latest
    container_name: qbittorrent
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Canada/Pacific
      - WEBUI_PORT=8990
      - TORRENTING_PORT=6881
    group_add:
      - "1001"
    volumes:
      - qbit_config:/config
      - /media/downloads/torrents:/data/downloads/torrents
      - /mnt/storage/media/downloads/torrents:/nasdata/downloads/torrents
    ports:
      - 8990:8990
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    # networks:
    #   docker_macvlan:
    #       ipv4_address: 10.0.1.21
    #   docker_vlan_bridge:
    #       ipv4_address: 10.0.10.21

  ####
  # requesters
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Canada/Pacific
    volumes:
      - overseerr_config:/config
    ports:
      - 5055:5055
    restart: unless-stopped
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=1001
      - PGID=1001
      - LOG_LEVEL=debug
      - TZ=Canada/Pacific
    ports:
        - 5051:5055
    volumes:
        - jellyseerr_config:/app/config
    restart: unless-stopped
     
volumes:
  jellyfin_config:
    name: jellyfin_config
  radarr_config:
    name: radarr_config
  sonarr_config:
    name: sonarr_config
  lidarr_config:
    name: lidarr_config
  lidatube_config:
    name: lidatube_config
  jackett_config:
    name: jackett_config
  prowlarr_config:
    name: prowlarr_config
  overseerr_config:
    name: overseerr_config
  jellyseerr_config:
    name: jellyseerr_config
  qbit_config:
    name: qbit_config

# networks:
#   docker_macvlan:
#     external: true
#   docker_vlan_bridge:
#     external: true
# Here we define what networks are available to use by the services above
# Make sure to set the config of both macvlan and vlan_bridge as described in the guide.
# networks:
#   macvlan:
#     name: docker_macvlan
#     driver: macvlan
#     enable_ipv6: false
#     driver_opts:
#       parent: enp1s0f0
#     ipam:
#       config:
#         - subnet: 10.0.1.0/24 # Set to same subnet as your router and other devices
#           ip_range: 10.0.1.0/27 # Available range from 192-224
#           gateway: 10.0.1.1 # This is your router IP

#   vlan_bridge:
#     name: docker_vlan_bridge
#     driver: bridge
#     enable_ipv6: false
#     ipam:
#       config:
#         - subnet: 10.0.10.0/24 # subnet for all containers
#           ip_range: 10.0.10.0/27 # for easier use, set to same range as under macvlan (192 to 224 here)
#           gateway: 10.0.10.1 # for easier use, set to same last number as your router (1)
