version: "3"
services:
  plex:
    image:  linuxserver/plex:arm64v8-latest
    container_name: plex
    hostname: Plex
    environment:
      - PUID=1001
      - PGID=1001
      - VERSION=docker
      - PLEX_CLAIM=claim-NZbczaZ6F5WatMLiMUxP
    group_add:
      - "1001"
    volumes:
      - plex_config:/config
      - /media/tv:/tv
      - /media/movies:/movies
    restart: unless-stopped
    networks:
      docker_macvlan:
          ipv4_address: 10.0.1.10
      docker_vlan_bridge:
          ipv4_address: 10.0.10.10

  radarr:
    image: lscr.io/linuxserver/radarr:arm64v8-latest
    container_name: radarr
    hostname: radarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Canada/Pacific
    group_add:
      - "1001"
    volumes:
      - radarr_config:/config
      - /media/movies:/data/movies
      - /media/tv:/data/tv
      - /media/downloads:/data/downloads
    restart: unless-stopped
    networks:
      docker_macvlan:
          ipv4_address: 10.0.1.12
      docker_vlan_bridge:
          ipv4_address: 10.0.10.12

  jackett:
    image: lscr.io/linuxserver/jackett:arm64v8-latest
    container_name: jackett
    hostname: jackett
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Canada/Pacific
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - jackett_config:/config
      - /media/downloads/torrents:/data/downloads/torrents
    restart: unless-stopped
    networks:
      docker_macvlan:
          ipv4_address: 10.0.1.14
      docker_vlan_bridge:
          ipv4_address: 10.0.10.14

volumes:
  plex_config:
    name: plex_config
  radarr_config:
    name: radarr_config
  jackett_config:
    name: jackett_config

networks:
  docker_macvlan:
    external: true
  docker_vlan_bridge:
    external: true
